Gemfile.lock
app/controllers/api/v1/measurements_controller.rb
app/controllers/api/v1/parameters_controller.rb
app/controllers/api/v1/timelines_controller.rb
db/schema.rb
doc/api/measurements.md
doc/api/parameters.md
doc/api/timelines.md
spec/requests/api/measurements_spec.rb
spec/requests/api/parameters_spec.rb
spec/requests/api/timelines_spec.rb

Enable multiple values in certain API filter fields.

---

app/models/ground_type.rb
app/models/section.rb
app/serializer/section_serializer.rb
db/migrate/20150914102120_add_section_ground_type.rb
db/schema.rb
doc/api/sections.md
spec/factories.rb
spec/requests/api/sections_spec.rb

Extend data model with ground type info for sections

---

app/serializer/device_aggregation_serializer.rb
db/migrate/20150914111602_add_shape_to_device_aggregation.rb
db/schema.rb
doc/api/device_aggregations.md
spec/factories.rb
spec/requests/api/context_spec.rb
spec/requests/api/device_aggregation_spec.rb

Add shape attribute to device_aggregation. 

---

app/controllers/api/v1/fiber_optic_nodes_controller.rb
app/models/ability.rb
app/models/device.rb
app/models/fiber_optic_node.rb
app/serializer/fiber_optic_node_serializer.rb
app/views/help/api.html.haml
config/routes.rb
db/migrate/20150914124940_create_fiber_optic_nodes.rb
db/schema.rb
doc/api/fiber_optic_nodes.md
spec/factories.rb
spec/requests/api/fiber_optic_node_spec.rb
spec/support/matchers.rb

Create fiber optic nodes

---

app/controllers/api/v1/measurements_controller.rb
doc/api/measurements.md
spec/requests/api/measurements_spec.rb

Support limit flag in GET /measurements

---

app/serializer/device_serializer.rb
db/schema.rb
doc/api/devices.md
spec/requests/api/device_spec.rb

Device metadata API

---

app/controllers/api/v1/measurements_controller.rb

Fix possible division by 0 and SQL injection in measurements controller

---

app/controllers/api/v1/experiments_controller.rb
app/models/ability.rb
app/models/device.rb
app/models/experiment.rb
app/models/levee.rb
app/models/timeline.rb
app/serializer/experiment_serializer.rb
app/serializer/timeline_serializer.rb
app/views/help/api.html.haml
config/routes.rb
db/migrate/20151005102411_create_experiments.rb
db/migrate/20151005111952_add_label_to_timelines.rb
db/schema.rb
doc/api/experiments.md
doc/api/timelines.md
lib/tasks/create_sample_experiment.rake
spec/factories.rb
spec/models/experiment_spec.rb
spec/models/levee_spec.rb
spec/requests/api/budokop_sensors_spec.rb
spec/requests/api/context_spec.rb
spec/requests/api/device_aggregation_spec.rb
spec/requests/api/device_spec.rb
spec/requests/api/experiments_spec.rb
spec/requests/api/fiber_optic_node_spec.rb
spec/requests/api/neosentio_sensors_spec.rb
spec/requests/api/parameters_spec.rb
spec/requests/api/pump_spec.rb
spec/requests/api/sections_spec.rb
spec/support/matchers.rb

Add support for Experiment model

---

Gemfile
Gemfile.lock
app/controllers/api/v1/measurements_controller.rb
app/serializer/budokop_sensor_serializer.rb
app/serializer/context_serializer.rb
app/serializer/device_aggregation_serializer.rb
app/serializer/device_serializer.rb
app/serializer/edge_node_serializer.rb
app/serializer/experiment_serializer.rb
app/serializer/fiber_optic_node_serializer.rb
app/serializer/levee_serializer.rb
app/serializer/measurement_node_serializer.rb
app/serializer/measurement_serializer.rb
app/serializer/neosentio_sensor_serializer.rb
app/serializer/parameter_serializer.rb
app/serializer/profile_serializer.rb
app/serializer/pump_serializer.rb
app/serializer/result_serializer.rb
app/serializer/section_serializer.rb
app/serializer/sensor_serializer.rb
app/serializer/timeline_serializer.rb
app/serializer/weather_station_serializer.rb
config/initializers/active_model_serializers.rb

It will allow use to add cache to every object serialized into JSON. See https://github.com/rails-api/active_model_serializers#caching for details.

Update to active model serializers 0.10.0.rc3

---

app/controllers/api/v1/parameters_controller.rb
spec/requests/api/parameters_spec.rb

Accept levee_id as argument in GET /parameters

---

app/serializer/device_serializer.rb
app/serializer/parameter_serializer.rb
db/migrate/20151014184829_add_more_labels.rb
db/schema.rb

Creates fields which will later be used to identify time series and tags in influxdb.

Provide additional label fields in preparation of influxdb integration

---

app/models/experiment.rb
app/models/scenario.rb
app/models/timeline.rb
app/serializer/timeline_serializer.rb
db/migrate/20151019145120_extend_scenario_model.rb
db/schema.rb

Requested by @mkasztelnik @tbartynski

 Bind scenarios to experiments and timelines

---

app/controllers/api/v1/scenarios_controller.rb
app/models/ability.rb
app/models/context.rb
app/models/profile_type.rb
app/models/result.rb
app/models/scenario.rb
app/serializer/result_serializer.rb
app/serializer/scenario_serializer.rb
app/views/help/api.html.haml
config/routes.rb
db/migrate/20151021190104_update_scenario_model.rb
db/schema.rb
doc/api/results.md
doc/api/scenarios.md
spec/factories.rb
spec/requests/api/scenarios_spec.rb
spec/support/matchers.rb

Update scenario model

---

lib/tasks/aggregate_devices.rake

Reaggregate UT_P/UT_T and SV_P/SV_T devices

---

app/controllers/api/v1/results_controller.rb
app/controllers/api/v1/threat_assessment_runs_controller.rb
app/controllers/api/v1/threat_assessments_controller.rb
app/models/ability.rb
app/models/profile.rb
app/models/profile_selection.rb
app/models/result.rb
app/models/threat_assessment.rb
app/models/threat_assessment_run.rb
app/serializer/result_serializer.rb
app/serializer/threat_assessment_run_serializer.rb
app/serializer/threat_assessment_serializer.rb
config/routes.rb
db/migrate/20151024124347_refactor_threat_assessments.rb
db/schema.rb
doc/api/results.md
doc/api/threat_assessment_runs.md
doc/api/threat_assessments.md
spec/factories.rb
spec/requests/api/results_spec.rb
spec/requests/api/threat_assessment_runs_spec.rb
spec/requests/api/threat_assessments_spec.rb

Revamps the Threat Assessment model in DAP

Implement TB's new ThreatAssessment model and ancillary classes

---

lib/importers/scenarios_importer.rb
lib/tasks/scenarios_load.rake

Unfortunately it is quite time consuming process... If you have any proposition how it can be speeded up please let me know.
/cc @tbartynski, @nowakowski, @dharezlak

Loading scenarios from CSV files

---

lib/importers/scenarios_importer.rb
lib/tasks/scenarios_load.rake

* CSV column `scen` contains our DAP `Experiment` `name`
* CSV column `simul` contains our DAP 'Scenario` `name`

Inside CSV file there are both scenes and simulations

---

lib/tasks/fix_timelines.rake

Reassign real measurements to correct timelines.

---

app/controllers/api/v1/measurements_controller.rb
spec/requests/api/measurements_spec.rb

Handles empty lists in measurement request params

---

app/clock.rb
app/serializer/timeline_serializer.rb
app/services/earliest_measurement_service.rb
app/workers/earliest_measurement_worker.rb
config/application.rb
db/migrate/20160126141705_add_earliest_readings_to_timelines.rb
db/schema.rb
doc/api/timelines.md
spec/services/earliest_measurement_service_spec.rb

Earliest measurements

---

app/controllers/api/v1/measurements_controller.rb
db/schema.rb
spec/requests/api/measurements_spec.rb

Make sure to include latest measurement for each timeline when the quantity flag is used

---

app/controllers/api/v1/threat_levels_controller.rb
app/models/ability.rb
app/services/threat_level/assessment_run_status_data_builder_service.rb
app/services/threat_level/assessment_runs_data_builder_service.rb
app/services/threat_level/calculator_service.rb
app/services/threat_level/threat_assessment_runs_for_profile_service.rb
config/application.rb
config/routes.rb
db/migrate/20160704120738_add_timestamps_to_results.rb
db/schema.rb
doc/api/threat_levels.md
spec/requests/api/threat_levels_spec.rb
spec/services/threat_level/assessment_run_status_data_builder_service_spec.rb
spec/services/threat_level/threat_assessment_runs_for_profile_service_spec.rb
spec/services/threat_level/threat_level_assessment_runs_data_builder_service_spec.rb
spec/services/threat_level/threat_level_calculator_service_spec.rb

Threat levels

---

app/views/help/api.html.haml
db/schema.rb

Fixed api speciffication index - added threat_levels to the list

---

app/controllers/api/v1/threat_assessments_controller.rb
app/models/result.rb
app/models/threat_assessment.rb
db/migrate/20160817113721_add_status_to_threat_assessment.rb
db/schema.rb
doc/api/threat_assessments.md
spec/models/result_spec.rb
spec/requests/api/threat_assessments_spec.rb

Extend ThreatAssessment model with status field

---

lib/tasks/experiment.rake

Script for creating August experiment

---

app/controllers/api/v1/threat_levels_controller.rb
db/schema.rb
spec/requests/api/threat_levels_spec.rb

Add Threat Assessment status to threat_levels action

---

lib/exporters/experiment_exporter.rb

Introduced parameter id

---

lib/tasks/experiment.rake

Previous experiment was skipped due to technical levee problems. Current changes are connected with new experiment concept which already took place.
Experiment changes are already applied into prod and dev dap.

Update august experiment interval and water wave

---

app/controllers/api/v1/threat_levels_controller.rb
spec/requests/api/threat_levels_spec.rb

This will simplify UI (no additional dap query)

Add profile_id into threat level response

---

app/controllers/api/v1/threat_levels_controller.rb
doc/api/threat_levels.md
spec/requests/api/threat_levels_spec.rb

This is needed to highlight section with concrete alert level.

Add section_id into threat level response

---

app/controllers/api/v1/threat_levels_controller.rb
app/models/threat_assessment_run.rb
spec/requests/api/threat_levels_spec.rb

Close #137.
@nowakowski pay special attention to https://github.com/ismop/dap/blob/137_add_from_and_to_filtering/app/controllers/api/v1/threat_levels_controller.rb#L71-L84 since it was changed by SQL skill missing developer.

Add from and to filtering for Threat Assessments in ThreatLevels controller

---

app/controllers/api/v1/anomaly_data_controller.rb
app/services/anomaly/data_provider.rb
app/workers/anomaly/simple_detector.rb
config/dap.yml
config/initializers/dap_config.rb
config/routes.rb
doc/api/anomaly_data.md
spec/requests/api/anomaly_data_spec.rb
spec/services/anomaly/data_provider_spec.rb
spec/support/anomaly_shared_data.rb

Provides:
- a service for getting all data required for anomaly detection
- a REST action to get data required for anomaly detection
- simple anomaly detector
Closes #187

Anomaly detection
